---
name: Release

on:
  push:
    branches:
      - master

jobs:
  Release:
    runs-on: ubuntu-latest
    environment: Dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Semantic Release
        run: |
          npm install @semantic-release/git -D
          npm install @semantic-release/changelog -D

      - name: Run Semantic Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GHACTIONS_RELEASE }}
